### ISSUE TITLE
observation window size and consistency between layers

### ISSUE THREAD

**Issue by Cooperx521** [FasterDecoding/SnapKV#17]
Hello  :)

Thank you for the brilliant work and for sharing your code. After reading the paper and reviewing the related code, I have the following questions:

1. Have you conducted experiments related to the observation window size (e.g., sizes ranging from 1 to 64)? How does this impact the hit rates and overall model performance?
2. In the "layer-wise average hit rate" experiment, the hit rate of the middle layers is significantly lower than that of the shallow and deep layers. Do you know the reason for this?

Thank you for your excellent paper!

**Comment by WendyH1108** [comment]
1. In our experiment, we did try different observation window size (16, 32, 64, 128). As I observed, there is no significant effect/patterns on hit rate. 
2. I also have the similar observations on other project experiments. From my opinion, I think the deeper layers are relatively stable(which means higher hit rate) because the hidden states should more accurately approach to the final output hidden states.
