### ISSUE TITLE
Grouped query attention implementation

### ISSUE THREAD

**Issue by guozhiyu** [FasterDecoding/SnapKV#4]
Thank you for your nice work and sharing code. Grouped query attention is used in Mistral and Mixtral models. However, I found the implementation in `snapkv_utils.py` is  for multi-head attention, it may not be correct for grouped query attention.

**Comment by leeyeehoo** [comment]
Thank you for your comment! Since I refactored the codebase, you can refer to [the monkey patch](https://github.com/FasterDecoding/SnapKV/blob/ac2857b0305249b82e1a966c36e5407f2dfb5e49/snapkv/monkeypatch/mistral_hijack_4_37.py#L96). We change the order of `repeat_kv` so it should be correct. You can run the notebook example and test with mistral.
